import {useEffect,useState} from 'react';
import {api,save,query,Row,day,today} from './api';
const outcomes:Row={pass:'Utan anmärkning',fail:'Anmärkning',na:'Ej tillämpligt'};
export function InspectionsPage({p}:{p:any}){
 const [overview,setOverview]=useState<Row|null>(null);
 const [templates,setTemplates]=useState<Row>({}),[page,setPage]=useState(1),[list,setList]=useState<Row|null>(null),[selected,setSelected]=useState(''),[record,setRecord]=useState<Row|null>(null),[answers,setAnswers]=useState<Row>({}),[findings,setFindings]=useState<Row[]>([]),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let active=true;setOverview(null);api('inspections/overview/?'+query({org:p.org})).then(r=>{if(active)setOverview(r);}).catch(p.fail);return()=>{active=false;};},[p.org,p.tick]);
 useEffect(()=>{api('inspections/templates/').then(setTemplates).catch(p.fail);},[]);
 useEffect(()=>{let active=true;setList(null);api('inspections/?'+query({org:p.org,page})).then(r=>{if(active)setList(r);}).catch(p.fail);return()=>{active=false;};},[p.org,page,p.tick]);
 useEffect(()=>{setSelected('');setRecord(null);setDirty(false);setPage(1);},[p.org]);
 useEffect(()=>{let active=true;setRecord(null);setError('');setNotice('');setDirty(false);if(selected)api('inspections/'+selected+'/').then(r=>{if(active){setRecord(r);setAnswers(r.answers);}}).catch(p.fail);return()=>{active=false;};},[selected]);
 useEffect(()=>{let active=true;if(record){async function load(){let path='findings/?'+query({series:record!.series}),rows:Row[]=[];while(path){const r=await api(path);rows.push(...r.results);path=r.next?String(r.next).split('/api/v1/')[1]:'';}if(active)setFindings(rows);}load().catch(p.fail);}return()=>{active=false;};},[record,p.tick]);
 useEffect(()=>{const unload=(e:BeforeUnloadEvent)=>{if(dirty||busy){e.preventDefault();e.returnValue='';}};const leave=(e:Event)=>{if((dirty||busy)&&!confirm(busy?'En sparning eller uppladdning pågår. Lämna ändå?':'Du har osparade kontrollsvar. Lämna utan att spara?'))e.preventDefault();};addEventListener('beforeunload',unload);addEventListener('forvalta:before-navigate',leave);return()=>{removeEventListener('beforeunload',unload);removeEventListener('forvalta:before-navigate',leave);};},[dirty,busy]);
 const leave=()=>window.dispatchEvent(new Event('forvalta:before-navigate',{cancelable:true}));
 function edit(key:string,change:Row){setAnswers(a=>({...a,[key]:{result:'',note:'',documents:[],...a[key],...change}}));setDirty(true);setNotice('Osparade ändringar');}
 async function reload(){if(!selected)return;const r=await api('inspections/'+selected+'/');setRecord(r);setAnswers(r.answers);setDirty(false);p.refresh();}
 async function persist(){if(!record)return;setBusy(true);setError('');try{await save('inspections/'+record.id+'/',{version:record.version,answers},'PATCH');await reload();setNotice('Sparat på servern');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function publish(){if(!record||dirty)return;setBusy(true);setError('');try{await save('inspections/'+record.id+'/publish/',{version:record.version});await reload();setNotice('Protokollet är fastställt och låst.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function attach(key:string,file:File|undefined){if(!record||!file)return;setBusy(true);setError('');try{const body=new FormData();body.append('asset',record.asset);body.append('title',file.name);body.append('file',file);const result=await save('documents/',body);edit(key,{documents:[...(answers[key]?.documents||[]),result.id]});setNotice('Bilagan är uppladdad. Spara kontrollsvaren för att koppla den till punkten.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 function create(){p.setModal({title:'Planera besiktning',endpoint:'inspections/',fields:[{...p.fields.asset,type:'remote:assets',options:[]},{key:'title',label:'Namn',required:true},{key:'template',label:'Grundmall',type:'select',options:Object.entries(templates).map(([id,t])=>[id,t.name]),required:true},{key:'scheduled_date',label:'Planerat datum',type:'date',required:true,default:today()},{key:'items',label:'Egna kontrollpunkter · valfritt, en per rad',type:'lines'}],transform:(d:Row)=>{if(!d.items?.length)delete d.items;return d;}});}
 function followup(mode:string){if(!record)return;p.setModal({title:mode==='correction'?'Skapa rättelse':'Planera ombesiktning',endpoint:'inspections/'+record.id+'/followup/',fields:[{key:'reason',label:'Skäl / omfattning',type:'textarea',required:true},{key:'scheduled_date',label:'Datum',type:'date',default:today(),required:true}],initial:{version:record.version},transform:(data:Row)=>({...data,mode})});}
 async function verify(f:Row){if(!record)return;setBusy(true);setError('');try{await save('findings/'+f.id+'/verify/',{version:f.version,inspection:record.id});await reload();setNotice('Anmärkningen är verifierad.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const canEdit=record&&p.boot.edit_orgs.includes(record.org),canManage=record&&p.boot.manage_orgs.includes(record.org),locked=record?.state==='published';
 return <div className="inspection-page"><div className="page-heading"><div><div className="eyebrow">KONTROLL · ÅTGÄRD · VERIFIERING</div><h1>Besiktningsprotokoll</h1><p>Planera kontroller, dokumentera brister och följ upp åtgärder.</p></div></div>{error&&<p role="alert" className="ai-notice">{error}</p>}{notice&&<p role="status" className="inspection-save-status">{notice}</p>}
 {!selected?<>{overview&&<section className="panel padded"><h2>Kontrollöversikt</h2><p>{overview.planned} planerade · {overview.overdue} försenade · {overview.open_findings} öppna anmärkningar</p>{overview.findings.map((f:Row)=><button key={f.id} className="inspection-list-card" onClick={()=>setSelected(f.inspection_id)}>Öppen anmärkning: {f.title}</button>)}{overview.open_findings>20&&<p>Visar de 20 äldsta öppna anmärkningarna. Övriga finns i respektive protokoll.</p>}</section>}<button className="btn primary" onClick={create} disabled={!p.boot.edit_orgs.length}>Planera besiktning</button><p>Grundmallarna är arbetsstöd. Anpassa kontrollpunkterna till objektet och verksamhetens krav.</p>{!list?<p role="status">Läser kontroller…</p>:<><p>{list.count} kontroller</p>{list.results.map((r:Row)=><button className="inspection-list-card" key={r.id} onClick={()=>setSelected(r.id)}><strong>{r.title}</strong><span>{r.asset_name} · {day(r.scheduled_date)}</span><span>{r.state==='published'?'Fastställt':r.scheduled_date<today()?'Försenat utkast':'Planerat / utkast'}{r.follow_up_of?' · Ombesiktning':r.supersedes?' · Rättelse':''}</span></button>)}{!list.count&&<p>Inga besiktningar ännu. Börja med en grundmall.</p>}<div className="inline-actions"><button className="btn" disabled={!list.previous} onClick={()=>setPage(v=>v-1)}>Föregående</button><button className="btn" disabled={!list.next} onClick={()=>setPage(v=>v+1)}>Nästa</button></div></>}</>:<><button className="text-btn" onClick={()=>{if(leave())setSelected('');}}>← Alla besiktningar</button>{!record?<p role="status">Läser protokollet…</p>:<>
 <section className="panel padded"><h2>{record.title}</h2><p>{locked?record.snapshot.asset:record.asset_name} · {day(record.scheduled_date)} · {record.template_name}</p><p>{locked?'Fastställt och låst':'Utkast · alla punkter måste besvaras före fastställande'} · version {record.version}</p>{record.reason&&<p>Skäl: {record.reason}</p>}{(record.follow_up_of||record.supersedes)&&<button className="text-btn" onClick={()=>{if(leave())setSelected(record.follow_up_of||record.supersedes);}}>Öppna föregående protokoll</button>}
 <div className="inline-actions">{locked?<><a className="btn" href={'/api/v1/inspections/'+record.id+'/protocol/'}>Hämta PDF-protokoll</a>{canManage&&<><button className="btn" onClick={()=>followup('correction')}>Skapa rättelse</button><button className="btn primary" onClick={()=>followup('followup')}>Planera ombesiktning</button></>}</>:<><button className="btn primary" disabled={busy||!dirty||!canEdit} onClick={persist}>{busy?'Arbetar…':'Spara kontrollsvar'}</button>{canManage&&<button className="btn" disabled={busy||dirty} onClick={publish}>Fastställ och lås protokollet</button>}</>}</div></section>
 {record.items.map((item:Row,index:number)=>{const a=answers[item.key]||{};return <section className="panel padded inspection-point" key={item.key}><h3>{index+1}. {item.label}</h3><fieldset disabled={locked||busy||!canEdit}><legend>Kontrollresultat</legend><div className="inspection-results">{Object.entries(outcomes).map(([v,label])=><label key={v}><input type="radio" name={item.key} checked={a.result===v} onChange={()=>edit(item.key,{result:v})}/>{label}</label>)}</div><label>Kommentar {['fail','na'].includes(a.result)?'· obligatorisk':''}<textarea rows={3} maxLength={4000} value={a.note||''} onChange={e=>edit(item.key,{note:e.target.value})}/></label>{!locked&&<label>Foto eller bilaga · PDF, PNG, JPEG<input type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>{attach(item.key,e.target.files?.[0]);e.target.value='';}}/></label>}</fieldset><div className="inline-actions">{(a.documents||[]).map((id:string,i:number)=><a className="btn" key={id} href={'/api/v1/documents/'+id+'/download/'}>Hämta bilaga {i+1}</a>)}</div></section>;})}
 {!locked&&<div className="inspection-sticky"><span>{dirty?'Osparade kontrollsvar':'Inga osparade kontrollsvar'}</span><button className="btn primary" disabled={busy||!dirty||!canEdit} onClick={persist}>Spara kontrollsvar</button></div>}
 <section className="panel padded"><h2>Anmärkningar i denna kontrollserie</h2>{!findings.length&&<p>Anmärkningar skapas när protokollet fastställs.</p>}{findings.map(f=><article className="inspection-finding" key={f.id}><h3>{f.title}</h3><p>{f.note}</p><p>{f.state==='verified'?'Verifierad vid ombesiktning':'Öppen anmärkning'}</p><div className="inline-actions">{f.work?<button className="btn" onClick={()=>api('work/'+f.work+'/').then(w=>p.setDetail({type:'work',row:w})).catch(p.fail)}>Öppna arbetsorder</button>:canEdit&&f.state==='open'&&<button className="btn" onClick={()=>p.setModal({title:'Åtgärda: '+f.title,endpoint:'findings/'+f.id+'/order/',fields:[{key:'assigned_to',label:'Ansvarig utförare',type:'remote:users',options:[],required:true},{key:'due_date',label:'Sista åtgärdsdatum',type:'date',required:true},{key:'priority',label:'Prioritet',type:'select',options:[['low','Låg'],['normal','Normal'],['high','Hög'],['urgent','Akut']],default:'normal'}],initial:{version:f.version}})}>Skapa åtgärdsorder</button>}{canManage&&locked&&record.follow_up_of&&f.state==='open'&&<button className="btn primary" disabled={busy} onClick={()=>verify(f)}>Verifiera med denna ombesiktning</button>}</div></article>)}</section>
 </>}</>}
 </div>;
}
