import { useEffect, useState } from "react";
import { ArrowLeft, Plus, Building2, FileText, RefreshCw } from "lucide-react";
import { api, save, Row, money, day, kindNames, stateNames } from "./api";
const exactMoney=(value:any)=>value===null||value===undefined?'Saknas':new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value));
const tabs=[['overview','Översikt'],['objects','Byggnader & objekt'],['work','Arbete'],['schedules','Ronder & kontroller'],['maintenance','Underhåll'],['costs','Ekonomi'],['documents','Dokument'],['history','Historik']];
const entityNames:Row={asset:'Objekt',workorder:'Arbetsorder',workcomment:'Kommentar',schedule:'Återkommande kontroll',maintenance:'Underhåll',costentry:'Kostnadsrad',document:'Dokument',registryentry:'Registerpost'};
const eventNames:Row={created:'Skapad',updated:'Uppdaterad',status_changed:'Status ändrad',uploaded:'Uppladdad',downloaded:'Hämtad',generated:'Återkommande arbete skapat',maintenance_order:'Arbetsorder skapad från underhåll',order_linked:'Kopplad till arbetsorder',ai_priority_approved:'AI-förslag godkänt',schedule_advanced:'Nästa tillfälle framflyttat'};

export function PropertyWorkspace({p,selected,onSelect,onBack}:{p:any;selected:Row;onSelect:(r:Row)=>void;onBack:()=>void}) {
  const [summary,setSummary]=useState<Row|null>(null),[section,setSection]=useState('overview'),[page,setPage]=useState(1),[result,setResult]=useState<Row|null>(null),[status,setStatus]=useState(''),[search,setSearch]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const base='assets/'+selected.id+'/workspace/';
  useEffect(()=>{setSection('overview');setPage(1);setSearch('');setStatus('');},[selected.id]);
  useEffect(()=>{let alive=true;setSummary(null);setError('');api(base).then(r=>{if(alive)setSummary(r);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[base,p.tick]);
  useEffect(()=>{let alive=true;setResult(null);if(section!=='overview')api(base+'?'+new URLSearchParams({section,page:String(page),status:section==='work'?status:'',q:search})).then(r=>{if(alive)setResult(r);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[base,p.tick,section,page,status,search]);
  function switchTab(tab:string,filter=''){setSection(tab);setStatus(filter);setSearch('');setPage(1);setError('');}
  async function openObject(id:string){try{onSelect(await api('assets/'+id+'/'));}catch(e:any){setError(e.message);}}
  async function openWork(id:string){try{p.setDetail({type:'work',row:await api('work/'+id+'/')});}catch(e:any){setError(e.message);}}
  function upload(revision?:Row){p.setModal({title:revision?'Ny dokumentversion':'Ladda upp dokument',endpoint:'documents/',fields:[{key:'title',label:'Dokumentnamn',required:true},{key:'file',label:'Fil · PDF, PNG eller JPEG',type:'file',required:true}],initial:{asset:revision?.asset||selected.id,title:revision?.title||'',...(revision?{revision_of:revision.id}:{})}});}
  async function order(row:Row){setBusy(true);setError('');try{const r=await save('maintenance/'+row.id+'/order/',{version:row.version});p.refresh();await openWork(r.id);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  if(!summary)return <><button className="text-btn back" onClick={onBack}><ArrowLeft size={16}/>Alla fastigheter</button>{error?<p role="alert" className="ai-notice">{error}</p>:<p role="status">Läser fastighetens underlag…</p>}</>;
  const asset=summary.asset,perm=summary.permissions,counts=summary.counts;
  const childKind:Row={property:'building',building:'premises',premises:'room',room:'object',land:'object'};
  return <div className="property-workspace">
    <nav aria-label="Objekthierarki" className="property-crumbs"><button className="text-btn" onClick={onBack}><ArrowLeft size={15}/>Alla fastigheter</button>{summary.ancestors.map((a:Row)=><button className="text-btn" disabled={a.archived} key={a.id} onClick={()=>openObject(a.id)}>{a.name}</button>)}<span>{asset.name}</span></nav>
    <div className="property-heading"><div><div className="eyebrow">{kindNames[asset.kind]} · {asset.org_name}</div><h1>{asset.name}</h1><p>{asset.address||'Adress saknas'}</p></div><div className="inline-actions">{perm.manage&&<button className="btn" onClick={()=>p.openForm('assets',asset)}>Redigera uppgifter</button>}{perm.edit&&<button className="btn primary" onClick={()=>p.openForm('work',undefined,{asset:asset.id,org:asset.org})}><Plus size={16}/>Nytt ärende</button>}<button className="btn" aria-label="Uppdatera fastighetsvyn" onClick={p.refresh}><RefreshCw size={16}/></button></div></div>
    <p className="muted">{summary.scope}</p>
    {error&&<p role="alert" className="ai-notice">{error}</p>}
    <nav className="tabs property-tabs" aria-label="Fastighetens innehåll">{tabs.filter(([id])=>!(['maintenance','costs'].includes(id)&&!perm.finance)&&!(id==='history'&&!perm.history)).map(([id,label])=><button key={id} aria-current={section===id?'page':undefined} className={section===id?'selected':''} onClick={()=>switchTab(id)}>{label}</button>)}</nav>
    {section==='overview'?<>
      <div className="property-stats">{[['Öppna arbeten',counts.open,'work','open'],['Försenade',counts.overdue,'work','overdue'],['Väntar på verifiering',counts.awaiting_verification,'work','completed'],['Återkommande kontroller',counts.schedules,'schedules','']].map(([label,value,target,filter])=><button className="panel" key={label} onClick={()=>switchTab(String(target),String(filter))}><span>{label}</span><strong>{value}</strong><small>Visa underlag →</small></button>)}</div>
      <div className="two-column"><section className="panel padded"><h2>Fastighetsuppgifter</h2><dl>{[['Beteckning',asset.designation],['Ägare',asset.owner],['Förvaltare',asset.manager],['Registrerad area på objektet',asset.area===null?'Saknas':asset.area+' m²'],['Publik felanmälan',asset.public?'Aktiverad':'Inte aktiverad']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Saknas'}</dd></div>)}</dl><p>{asset.description}</p><p className="muted">Area summeras inte över byggnader och rum, för att undvika dubbelräkning.</p></section>
      <section className="panel padded"><h2>Samlat underlag</h2><button className="asset-child" onClick={()=>switchTab('objects')}><Building2 size={20}/><span>{counts.objects} underobjekt</span></button><button className="asset-child" onClick={()=>switchTab('documents')}><FileText size={20}/><span>{counts.documents} dokumentversioner</span></button>{perm.finance?<><h3>Registrerade kostnader {summary.costs.year}</h3><button className="text-btn" onClick={()=>switchTab('costs')}>{exactMoney(summary.costs.amount)} · {summary.costs.entries} kostnadsrader →</button><p>{summary.costs.definition}</p></>:<p>Ekonomiska underlag kräver separat ekonomibehörighet.</p>}<p className="muted">Hämtat {new Date(summary.generated_at).toLocaleString('sv-SE')}</p></section></div>
    </>:<section className="panel padded">
      <div className="property-list-heading"><h2>{tabs.find(t=>t[0]===section)?.[1]}</h2><div className="inline-actions">{section==='objects'&&perm.manage&&childKind[asset.kind]&&<button className="btn" onClick={()=>p.openForm('assets',undefined,{parent:asset.id,org:asset.org,kind:childKind[asset.kind]})}>Lägg till underobjekt</button>}{section==='documents'&&perm.edit&&<button className="btn" onClick={()=>upload()}>Ladda upp på {asset.name}</button>}{section==='maintenance'&&perm.manage&&<button className="btn" onClick={()=>p.openForm('maintenance',undefined,{asset:asset.id,org:asset.org})}>Ny underhållsåtgärd</button>}{section==='schedules'&&perm.manage&&<button className="btn" onClick={()=>p.openForm('schedules',undefined,{asset:asset.id,org:asset.org})}>Ny återkommande kontroll</button>}</div></div>
      {section==='costs'&&<p>{summary.costs.definition} År: {summary.costs.year}.</p>}{section==='maintenance'&&<p>Registrerade grundåtgärder och deras beräknade belopp för planerat år. Återkommande åtgärder och flerårsscenarier visas under Underhåll & budget.</p>}{section==='history'&&<p>Spårbara händelser för objekt, arbetsorder, kommentarer, kontroller, dokument och register. Ekonomiska händelser visas endast med ekonomibehörighet. Händelsernas innehåll exponeras inte här.</p>}
      <div className="property-filters">{section!=='history'&&<label>Sök i listan<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Rubrik eller namn"/></label>}{section==='work'&&<label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Alla statusar</option><option value="open">Öppna</option><option value="overdue">Försenade</option>{Object.entries(stateNames).filter(([key])=>['new','planned','in_progress','completed','verified','cancelled'].includes(key)).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label>}</div>
      {!result?<p role="status">Läser poster…</p>:<><p>{result.count} poster · sida {page}</p>{!result.results.length?<p>Inga poster matchar urvalet.</p>:<div className="property-rows">{result.results.map((r:Row)=><article key={r.id} className="property-row"><div>
        <h3>{section==='objects'?<button className="text-btn" onClick={()=>openObject(r.id)}>{r.name}</button>:section==='work'?<button className="text-btn" onClick={()=>openWork(r.id)}>#{r.number} {r.title}</button>:section==='history'?eventNames[r.action]||r.action:r.title||r.description}</h3>
        <p>{section==='objects'?kindNames[r.kind]:r.asset_name||''}{r.archived?' · Arkiverad':''}</p>
        {section==='work'&&<p>{stateNames[r.status]} · {day(r.due_date)} · {r.assigned_name||'Ej tilldelad'}</p>}
        {section==='schedules'&&<p>{kindNames[r.kind]} · Nästa tillfälle {day(r.next_date)}</p>}
        {section==='maintenance'&&<p>{r.year} · {r.quantity} {r.unit} × {exactMoney(r.unit_price)} · Beräknat belopp {money(r.planned_amount)}</p>}
        {section==='costs'&&<p>{day(r.date)} · {r.quantity} × {exactMoney(r.unit_price)} · {exactMoney(r.total)} · Arbetsorder {r.work}</p>}
        {section==='documents'&&<p>{day(r.created_at)} · {Math.ceil(r.size/1024)} kB · {r.revision_of?'Ny version av befintligt dokument':'Originalversion'}</p>}
        {section==='history'&&<p>{new Date(r.created_at).toLocaleString('sv-SE')} · {r.actor__username||'Systemet'} · {entityNames[r.entity]||'Registerpost'}{r.label?' · '+r.label:''}</p>}
      </div><div className="inline-actions">
        {section==='documents'&&<><a className="btn" href={'/api/v1/documents/'+r.id+'/download/'}>Hämta</a>{perm.edit&&<button className="btn" onClick={()=>upload(r)}>Ny version</button>}</>}
        {section==='maintenance'&&(r.work?<button className="btn" onClick={()=>openWork(r.work)}>Öppna arbetsorder</button>:perm.manage&&<button className="btn primary" disabled={busy} onClick={()=>order(r)}>Skapa arbetsorder</button>)}
        {['maintenance','schedules'].includes(section)&&perm.manage&&<button className="btn" onClick={()=>p.openForm(section,r)}>Redigera</button>}
        {section==='costs'&&<button className="btn" onClick={()=>openWork(r.work)}>Öppna arbetsorder</button>}
      </div></article>)}</div>}<div className="inline-actions"><button className="btn" disabled={!result.previous} onClick={()=>setPage(n=>n-1)}>Föregående</button><button className="btn" disabled={!result.next} onClick={()=>setPage(n=>n+1)}>Nästa</button></div></>}
    </section>}
  </div>;
}
