import {useEffect,useState} from 'react';
import {api,query,Row} from './api';
export const groupChoices:Row={work:['Organisation','Objekt','Status','Utförare','Typ'],overdue:['Organisation','Objekt','Status','Utförare','Typ'],rounds:['Organisation','Objekt','Status','Utförare'],inspections:['Organisation','Objekt','Status','Utförare'],budget:['Organisation','Objekt','År','Kontering'],maintenance:['Organisation','Objekt','År','Kontering'],assets:['Organisation','Typ'],invoices:['Typ','Datum'],registry:['Objekt','Typ','Status'],nki:['Objekt','Status'],keys:['Objekt'],energy:['Objekt','Mätare','Enhet']};
export const measureChoices=(type:string)=>['Antal',...(['budget','maintenance'].includes(type)?['Budget','Möjlig finansiering','Beviljad finansiering']:type==='invoices'?['Belopp']:[])];
const value=(v:any)=>v===null||v===undefined?'Saknas':String(v);
const amount=(v:any)=>v===null||v===undefined?'Saknas':new Intl.NumberFormat('sv-SE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v))+' kr';

export function GroupDetails({report,p}:{report:Row;p:any}){
 const [selected,setSelected]=useState<string|null>(null);useEffect(()=>setSelected(null),[report]);
 const a=report.analysis;if(!a)return null;
 const max=Math.max(1,...a.groups.map((r:Row)=>Number(r.Värde||0)));
 const rows=selected===null?[]:(a.members[selected]||[]).map((i:number)=>report.detail_rows[i]);
 return <section className="group-details"><h3>{a.measure} per {a.group_by}</h3><p>{a.definition} Enhet: {a.unit}. Klicka på en grupp för underlaget.</p><div className="group-bars">{a.groups.map((r:Row)=><button className={selected===r.id?'chosen':''} key={r.id} onClick={()=>setSelected(r.id)}><span>{value(r.Grupp)}</span><span className="group-bar" aria-hidden="true"><i style={{width:(100*Number(r.Värde||0)/max)+'%'}}/></span><strong>{a.unit==='SEK'?amount(r.Värde):value(r.Värde)}</strong></button>)}</div>
 {selected!==null&&<div className="group-source"><h3>Underlag: {value(a.groups.find((r:Row)=>r.id===selected)?.Grupp)} · {rows.length} poster</h3><button className="text-btn" onClick={()=>setSelected(null)}>Stäng underlaget</button><div className="table-wrap"><table><thead><tr>{Object.keys(rows[0]||{}).filter(k=>k!=='id').map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.map((r:Row,i:number)=><tr key={r.id+':'+i}>{Object.entries(r).filter(([k])=>k!=='id').map(([k,v])=><td key={k}>{k==='Rubrik'&&['work','overdue','rounds','inspections'].includes(report.type)?<button className="text-btn" onClick={()=>api('work/'+r.id+'/').then(w=>p.setDetail({type:'work',row:w})).catch(p.fail)}>{value(v)}</button>:value(v)}</td>)}</tr>)}</tbody></table></div></div>}
 </section>;
}

export function ScenarioComparison({p,scenarios}:{p:any;scenarios:Row[]|null}){
 const [left,setLeft]=useState(''),[right,setRight]=useState(''),[report,setReport]=useState<Row|null>(null),[error,setError]=useState(''),[onlyChanged,setOnlyChanged]=useState(true);
 useEffect(()=>{setLeft('');setRight('');setReport(null);setError('');},[p.org]);
 useEffect(()=>{let active=true;setReport(null);setError('');if(left&&right)api('scenarios/'+left+'/compare/?'+query({other:right})).then(r=>{if(active)setReport(r);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[left,right,p.tick]);
 const source=scenarios?.find(s=>s.id===left);
 const labels:Row={draft:'Utkast',published:'Fastställd'};
 return <section className="panel padded"><h2>Jämför budgetversioner</h2><p>Välj före och efter med samma organisationsomfång och tidsperiod. Jämförelsen ändrar inga uppgifter.</p><div className="report-controls"><label>Före<select value={left} onChange={e=>setLeft(e.target.value)}><option value="">Välj version</option>{scenarios?.map(s=><option key={s.id} value={s.id}>{s.name} · {labels[s.state]} · {s.start_year}–{s.start_year+s.years-1}</option>)}</select></label><label>Efter<select value={right} onChange={e=>setRight(e.target.value)}><option value="">Välj version</option>{scenarios?.map(s=><option key={s.id} value={s.id}>{s.name} · {labels[s.state]} · {s.start_year}–{s.start_year+s.years-1}</option>)}</select></label>{source&&p.boot.manage_orgs.includes(source.org)&&<button className="btn" onClick={()=>p.setModal({title:'Skapa utkast från '+source.name,endpoint:'scenarios/'+source.id+'/clone/',fields:[{key:'name',label:'Namn på nytt utkast',required:true}],initial:{name:source.name+' – alternativ',version:source.version}})}>Kopiera före-version till nytt utkast</button>}{(scenarios as any)?.loadMore&&<button className="btn" onClick={(scenarios as any).loadMore}>Hämta fler versioner</button>}</div>
 {error&&<p role="alert" className="ai-notice">{error}</p>}{left&&right&&!error&&!report&&<p role="status">Beräknar jämförelsen…</p>}
 {report&&<><div className="comparison-totals">{Object.entries(report.totals).map(([k,v])=><div key={k}><span>{k}</span><strong>{amount(v)}</strong></div>)}</div><p>{report.definitions}</p><p>Skapad {new Date(report.generated_at).toLocaleString('sv-SE')} · {report.calculation_version} · Före version {report.filters.before.version}, efter version {report.filters.after.version}</p><div className="inline-actions">{['csv','xlsx','pdf'].map(fmt=><a className="btn" key={fmt} href={'/api/v1/scenarios/'+left+'/compare/?'+query({other:right,format_file:fmt,before_version:report.filters.before.version,after_version:report.filters.after.version})}>Hämta {fmt.toUpperCase()}</a>)}</div>
 <h3>Fördelning per år</h3><div className="table-wrap"><table><thead><tr><th>År</th><th>Före</th><th>Efter</th><th>Skillnad</th></tr></thead><tbody>{report.per_year.map((r:Row)=><tr key={r.year}><td>{r.year}</td><td>{amount(r.before)}</td><td>{amount(r.after)}</td><td>{amount(r.difference)}</td></tr>)}</tbody></table></div>
 <h3>Åtgärder</h3><label className="ai-check"><input type="checkbox" checked={onlyChanged} onChange={e=>setOnlyChanged(e.target.checked)}/>Visa bara ändrade rader · exporten innehåller samtliga rader</label>{report.rows.filter((r:Row)=>!onlyChanged||r.Förändring!=='Oförändrad').map((r:Row)=><article className="comparison-row" key={r.id}><h3>{r.Åtgärd} · {r.Förändring}</h3><p>{r.Objekt} · År {value(r['År före'])} → {value(r['År efter'])} · Budget {amount(r['Budget före'])} → {amount(r['Budget efter'])} · Skillnad {amount(r['Skillnad SEK'])}</p><details><summary>Visa ändrade fält</summary><table><thead><tr><th>Fält</th><th>Före</th><th>Efter</th></tr></thead><tbody>{report.details.find((d:Row)=>d.id===r.id)?.changes.map((d:Row)=><tr key={d.field}><td>{d.field}</td><td>{value(d.before)}</td><td>{value(d.after)}</td></tr>)}</tbody></table></details></article>)}{onlyChanged&&report.rows.every((r:Row)=>r.Förändring==='Oförändrad')&&<p>Inga ändrade åtgärder mellan versionerna.</p>}</>}
 </section>;
}
