# Generated by Django 5.2.17 on 2026-10-01 17:20

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_membership_active_membership_version_accountsecurity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(default=False)),
                ('endpoint', models.URLField(default='https://api.openai.com/v1')),
                ('model', models.CharField(blank=True, max_length=120)),
                ('encrypted_api_key', models.TextField(blank=True)),
                ('daily_limit', models.PositiveIntegerField(default=100)),
                ('allow_changes', models.BooleanField(default=False)),
                ('organizations', models.ManyToManyField(blank=True, to='core.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=core.models.uid, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('state', models.CharField(default='pending', max_length=16)),
                ('encrypted_result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_ai_request')],
            },
        ),
    ]
