# Generated by Django 5.2.17 on 2026-10-01 18:13

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aiconfiguration_airequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=core.models.uid, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.UUIDField(default=core.models.uid, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('scheduled_date', models.DateField()),
                ('template_name', models.CharField(max_length=100)),
                ('items', models.JSONField(default=list)),
                ('answers', models.JSONField(default=dict)),
                ('state', models.CharField(default='draft', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('snapshot', models.JSONField(default=dict)),
                ('published_at', models.DateTimeField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.asset')),
                ('follow_up_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='followups', to='core.inspection')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.orgunit')),
                ('supersedes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='core.inspection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionFinding',
            fields=[
                ('id', models.UUIDField(default=core.models.uid, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.UUIDField()),
                ('item_key', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=300)),
                ('note', models.TextField()),
                ('state', models.CharField(default='open', max_length=20)),
                ('verified_at', models.DateTimeField(null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.inspection')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.orgunit')),
                ('verification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_findings', to='core.inspection')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workorder')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('series', 'item_key'), name='unique_inspection_finding')],
            },
        ),
    ]
